version: '3.8'

services:
  web:
    build: .
    container_name: ev_supply_chain_app
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
